services:
  - type: web
    name: spidey-bot
    runtime: node
    runtimeVersion: 18
    plan: free
    buildCommand: npm install --no-audit --no-fund && npm run build
    startCommand: npm run prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: TOKEN
      - key: CLIENT_ID
      - key: CLIENT_SECRET
      - key: SESSION_SECRET
      - key: BASE_URL
      - key: FORCE_REDIRECT_URI
      - key: OPENAI_API_KEY
        value: sk-f34jbbyOYG5teUvBpUOGwvzfl8ydSmXbcOEYEnIRlUXb4J7P
